version: '3'
services: 
    web:
        build: .
        ports: 
            - '8081:8081'
    ipfs:
        image: ipfs/go-ipfs:latest
        ports:
            - '8080:8080'
            - '4001:4001'
            - '5001:5001'
        volumes:
            - 'ipfs:/data'
            - 'ipfs:/staging'
volumes:
    ipfs: